# 全局配置
global:
  chinese:
    enable: true
  hover:
    scale: true
  scroll_progress:
    bar: true
  busuanzi_counter:
    enable: false

# 基本信息
info:
  title: Yolo乀Blog
  author: hzihhuang
  url: https://super-zihao.github.io/blog

# 默认图片
defaults:
  avatar: ./assets/images/photos/渔人码头1.jpg
  logo: ./assets/images/logo.png
  favicon: ./assets/images/logo.png
# 颜色配置
colors:
  primary: #FF9671

# 顶部导航栏配置
navbar:
  auto_hide: false # 顶部是否自动隐藏
  links:
    归档:
      icon: fa-regular fa-archive
      path: /archives/
    标签:
      icon: fa-regular fa-tags
      path: /tags/
    分类:
      icon: fa-regular fa-folder
      path: /categories/
    关于我:
      icon: fa-regular fa-user
      path: /about/
    其他:
      icon: fa-solid fa-link
      submenus:
        特色组件: https://super-zihao.github.io/HDesign
        照片墙: /masonry/

# 首页
home:
  sidebar: # 侧边栏
    position: right
    announcement: 做一个温柔的人，浅浅笑，轻轻爱 # 公告
    links: # 左侧导航栏
      归档:
        icon: fa-solid fa-archive
        path: ./archives
      标签:
        icon: fa-solid fa-tags
        path: ./tags
      分类:
        icon: fa-solid fa-folder
        path: ./categories
      关于我:
        icon: fa-solid fa-user
        path: ./about

# 首页第一屏
home_banner:
  style: fixed
  title: 愿我们想要的都得到，得到的都美好。
  subtitle:
    text: [
      '内心丰盈者，独行也如众',
      '理想的生活需要一点热爱和心动',
      '理想主义的少年永远不会向现实招安。',
      '在人生的道路上，想哭就哭，想笑就笑吧，但是千万别忘记了赶路',
      '喜欢就争取，的到就珍惜，错过就忘记。',
      '你所期盼的都会稳稳妥妥的到来'
    ]
    typing_speed: 40
    backing_speed: 40
    starting_delay: 800 # 开始延迟（毫秒）
    backing_delay: 5000 # 退格延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true #是否智能退格
  image: # 背景图
    light: https://images.pexels.com/photos/290263/pexels-photo-290263.jpeg?auto=compress&cs=tinysrgb&w=1600
    dark: https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&w=1600
  social_links: # 社交
    enable: true
    links:
      [github]: https://github.com/Super-ZiHao
      [fa-solid fa-envelope]: mailto:hzihhuang@gmail.com
    qrs:
      [weixin]: ./assets/images/微信二维码.jpg
      [qq]: ./assets/images/QQ二维码.jpg

# 页脚
footer:
  start: 2023/8/11 17:40:14

# 作者标签
articles:
  author_label:
    enable: true
    auto: true
  recommendation: # 推荐文章
    enable: true

# 评论系统
comment:
  enable: true
  system: giscus
  config:
    giscus:
      repo: Super-ZiHao/blog
      repo_id: R_kgDOKF8XYQ
      category: General
      category_id: DIC_kwDOKF8XYc4CYkim
      mapping: title
      strict: 0
      reactions-enabled: 1
      emit-metadata: 0
      lang: zh-CN
      input_position: bottom
      loading: not-lazy

# 自定义样式
inject:
  enable: true
  footer: 
    - <link rel="stylesheet" href="/blog/assets/css/footer.css?1" />

# 插件
plugins:
  aplayer: # 音乐播放器
    enable: true
    type: fixed
    audios:
      - name: 亦是此间少年
        artist: 枯木逢春
        url: /blog/assets/backgroundMusics/亦是此间少年.mp3
        cover: https://p1.music.126.net/415A5Xt3bUegx4vyiY8dNQ==/109951164821961505.jpg?param=130y130
      - name: 盐 (Witch’s Condiment)
        artist: 沈以诚
        url: /blog/assets/backgroundMusics/盐.mp3
        cover: https://p1.music.126.net/gKb2PcbOKD6u89yRt_9HrQ==/109951165347972122.jpg?param=130y130
      - name: 夜色滚烫
        artist: 烦烦
        url: /blog/backgroundMusics/夜色滚烫.mp3
        cover: https://p2.music.126.net/UNQ0zGmQEhaIwh2ngGmaqw==/109951167964721730.jpg?param=177y177
      # - name:
      #   artist:
      #   url: 
      #   cover:
      # - name: 
      #   artist: 
      #   url: 
      #   cover:

        